docs: add Changelog for Ireland release
edgexfoundry/device-camera-go pull request #119
Opened 2021-06-25 12:33 UTC by cloudxxx8

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-camera-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

## Issue Number:
Fix #118

2021-06-25 17:03 UTC, lenny-intel requested changes

2021-06-25 17:03 UTC, lenny-intel commented on CHANGELOG.md
> +- Remove retry items of SecretStore config and update secret path - go-mod-bootstrap has implemented the addition of prefix /v1/secret/edgex/ for the Path property of SecretStore config section, so w
Remove as these are dev churn during dev cycle

2021-06-25 17:03 UTC, lenny-intel commented on CHANGELOG.md
> +- **snap:** update snap v2 support ([#5a3c97e](https://github.com/edgexfoundry/device-camera-go/commits/5a3c97e))
Should be under Build section

2021-06-25 17:03 UTC, lenny-intel commented on CHANGELOG.md
> +- bump dependency version and update import path ([#9562c59](https://github.com/edgexfoundry/device-camera-go/commits/9562c59))
Remove as it is dev churn

2021-06-25 17:03 UTC, lenny-intel commented on CHANGELOG.md
> +- Change PublishTopicPrefix value to be 'edgex/events/device' ([#0734506](https://github.com/edgexfoundry/device-camera-go/commits/0734506))
Remove as it is dev churn

2021-06-25 17:12 UTC, lenny-intel commented
Please add `Change Logs for EdgeX Dependencies` section like on ASC and App SDK change log
https://github.com/edgexfoundry/app-service-configurable/blob/master/CHANGELOG.md
https://github.com/edgexfoundry/app-functions-sdk-go/blob/master/CHANGELOG.md

Please make all all these same changes (above and in comments) to the other change logs. THX!

2021-06-27 07:32 UTC, cloudxxx8 commented
@lenny-intel 
In the app service CHANGELOGS
https://github.com/edgexfoundry/app-service-configurable/blob/master/CHANGELOG.md
https://github.com/edgexfoundry/app-functions-sdk-go/blob/master/CHANGELOG.md

We should use v2.0.0 tags instead of the master tags because `master` branch will be renamed to `main` branch
Also, the URL of go-mod-configuration is wrong

- [go-mod-bootstrap](https://github.com/edgexfoundry/go-mod-bootstrap/blob/master/CHANGELOG.md)
- [go-mod-core-contracts](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/CHANGELOG.md)
- [go-mod-messaging](https://github.com/edgexfoundry/go-mod-messaging/blob/master/CHANGELOG.md)
- [go-mod-registry](https://github.com/edgexfoundry/go-mod-registry/blob/master/CHANGELOG.md) 
- [go-mod-configuration](https://github.com/edgexfoundry/go-mod-configuration) (indirect dependency)
- [go-mod-secrets](https://github.com/edgexfoundry/go-mod-secrets/blob/master/CHANGELOG.md) (indirect dependency)

should become

- [go-mod-bootstrap](https://github.com/edgexfoundry/go-mod-bootstrap/blob/v2.0.0/CHANGELOG.md)
- [go-mod-core-contracts](https://github.com/edgexfoundry/go-mod-core-contracts/blob/v2.0.0/CHANGELOG.md)
- [go-mod-messaging](https://github.com/edgexfoundry/go-mod-messaging/blob/v2.0.1/CHANGELOG.md)
- [go-mod-registry](https://github.com/edgexfoundry/go-mod-registry/blob/v2.0.0/CHANGELOG.md)
- [go-mod-configuration](https://github.com/edgexfoundry/go-mod-configuration/blob/v2.0.0/CHANGELOG.md) (indirect dependency)
- [go-mod-secrets](https://github.com/edgexfoundry/go-mod-secrets/blob/v2.0.0/CHANGELOG.md) (indirect dependency)

2021-06-28 23:39 UTC, lenny-intel approved these changes
LGTM

2021-06-28 23:39 UTC, merged