fix(snap): Update versioning mechanism in snapcraft.yaml
edgexfoundry/device-camera-go pull request #62
Opened 2020-11-06 17:34 UTC by siggiskulason

This fix contains three minor changes to the way version numbers are generated when building the snap:
1) Git tag and datestamp have been removed from the version number. The version number is therefore now just "1.1.3-dev.5", as opposed to "1.1.3-dev.4-20201021+856f4f8"
2) Instead of using "version-script" (which has been deprecated) we now use "snapcraftctl set-version"
3) Instead of using "shell cat", we now use "cat" as otherwise the VERSION file may not be found, depending on the build setup.

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

The snap version is in the format "1.1.3-dev.4-20201021+856f4f8"
Issue Number:

## What is the new behavior?

The snap version will be in the format "1.1.3-dev.4"

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-11-06 22:24 UTC, tonyespy requested changes
Changes look good, the only thing I'd update is your commit message and drop the explicit mention of snapcraft.yaml. In general it's nice to keep the commit message summary short and to the point. What files have been modified can be seen using `git show` or `git diff`.

Suggest:

`fix(snap): update snap versioning logic
`

2020-11-09 15:03 UTC, siggiskulason commented
Thanks @tonyespy, that's a good point. I've updated the commit message and the title of this PR to match. Could you merge this PR please if you are ok with the change?

2020-11-09 22:19 UTC, lenny-intel commented on snap/snapcraft.yaml
> +        PROJECT_VERSION=local-dev
Same question as on the REST DS, should this be `0.0.0` as that is what the service will report.

2020-11-10 11:18 UTC, siggiskulason commented on snap/snapcraft.yaml
> +        PROJECT_VERSION=local-dev
Good point, thanks - I've responded in the Rest DS PR

2020-11-10 15:21 UTC, siggiskulason commented
I've updated the commit to use "0.0.0" instead of "local-dev", rebased the branch and pushed again.

2020-11-10 18:57 UTC, tonyespy approved these changes
LGTM

2020-11-10 22:41 UTC, lenny-intel approved these changes

2020-11-10 22:41 UTC, merged