refactor: update device-camera to consume v2 sdk
edgexfoundry/device-camera-go pull request #93
Opened 2021-05-26 04:23 UTC by hahattan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-camera-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

## Issue Number: fix #80 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions

## Other information

2021-05-26 09:50 UTC, hahattan commented on Readme.md
>  #### Integrate Into Applications
FYI this section needs update/rewrite as well. I'm not familiar with app-service so maybe someone do it in another PR?

2021-05-26 18:39 UTC, lenny-intel requested changes

2021-05-26 18:39 UTC, lenny-intel commented on Readme.md
> +    ```
This all can be replaced with reference to using compose builder to generate the compose file with device-camera added. 
```
clone edgex-compose
checkout release branch, i.e. hanoi 
cd compose-builder folder
run 'make gen no-secty ds-camera'

2021-05-26 18:39 UTC, lenny-intel commented on Readme.md
>  #### Integrate Into Applications
Yea, it just needs to reference https://github.com/edgexfoundry/edgex-examples/tree/master/application-services/custom/simple-cbor-filter. No need to clone the SDK, just need to build the example, but adding it to the compose file is not trivial these days. Not sure if this is all really needed. I.e. don't have it for our Device Services. Thoughts? 

The app service can just run from command-line for example purposes.

2021-05-26 18:39 UTC, lenny-intel commented on cmd/res/devices/camera.toml
> +#      Address = '192.168.2.163'
Can we remove this commented out config? If not it needs to be fixed, i.e. duplicate name and missing `[[DeviceList]]` to start the block.

2021-05-26 18:39 UTC, lenny-intel commented on cmd/res/profiles/camera-axis.yaml
> +  - name: "OnvifDeviceInformation"
Do we really need Device Commands specified for single resources., i.e. they are created by default. Or is it needed to restrict to read-only? If this is the case then the resource should have `isHidden: true` 

This applies to all the Read Device Commands for single resources here and the other profiles.

2021-05-26 18:39 UTC, lenny-intel commented on internal/driver/driver.go
> +			cv, _ := sdkModel.NewCommandValue(reqs[i].DeviceResourceName, v2.ValueTypeString, string(data))
Should not ignore the error here and below.

refactor to add error handling after switch and move `responses[i] = cv` to after switch so it isn't repeated in every case.

2021-05-26 18:39 UTC, lenny-intel commented on internal/driver/driver.go
>  			if err != nil {
Move to after switch and generic message like `error creating CommandValue`

2021-05-26 18:39 UTC, lenny-intel commented on internal/driver/driver_test.go
>  func (m *mockLogger) SetLogLevel(logLevel string) error {
Replace with use of mock from go-mod-core-contracts.
```
logger.NewMockClient()
```

2021-05-26 18:39 UTC, lenny-intel commented on internal/pkg/bosch/rcp.go
> +		alarmType, ok := e.Attributes["alarm_type"].(string)
What will happen with the `.(string) if "alarm_type" doesn't exist? Panic? Cast may need to happen only when `ok`?

2021-05-27 01:38 UTC, hahattan commented on cmd/res/devices/camera.toml
> +#      Address = '192.168.2.163'
removed.

2021-05-27 02:30 UTC, hahattan commented on internal/pkg/bosch/rcp.go
> +		alarmType, ok := e.Attributes["alarm_type"].(string)
Will not panic, in this case it would return zero-value and false.

2021-05-27 02:49 UTC, hahattan commented on cmd/res/profiles/camera-axis.yaml
> +  - name: "OnvifDeviceInformation"
> Or is it needed to restrict to read-only?

Considering nearly all deviceResources have RW privileges don't think that's the case.
Maybe the deviceCommands were created for uniform format? (deviceResources have both snake_case and CamelCase)
I'm gonna remove all deviceCommands to reduce complexity for now.

2021-05-27 03:41 UTC, hahattan commented on Readme.md
>  #### Integrate Into Applications
Yeah I don't think make it a container is necessary, running the binary seems enough for example purposes.

2021-05-27 16:21 UTC, siggiskulason requested changes
There are a few minor things that need to be fixed for the snap to build. See my inline comments and also,

In line 56 in snapcraft, yaml, replace

```
    build-packages: [git]
```

with

```
    build-packages: [git, libzmq3-dev, pkg-config]
    stage-packages: [libzmq5]
```
Also just wanted to note, that even with those changes (adding the stage-packages) I'm getting an error which I've also seen in other device services:

```
May 27 17:18:05 sidar-XPS-8930 edgex-device-camera.device-camera[751631]: /snap/edgex-device-camera/x1/bin/device-camera: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
```
I am investigating that separately, to see if it's an issue with all the v2 device snaps - and if so, how to resolve it. That shouldn't necessarely hold up this PR - I can create a new PR with fixes for all snaps for that, if needed.

2021-05-27 16:21 UTC, siggiskulason commented on snap/hooks/install
> +        "$SNAP_DATA/config/device-camera/res/profiles"
this copies the profiles directory, so we end up with $SNAP/config/device-camera/res/profiles/profiles/ 
The target should just be the res directory, i.e

```
 cp -r "$SNAP/config/device-camera/res/profiles/" \
        "$SNAP_DATA/config/device-camera/res"
```

2021-05-27 16:21 UTC, siggiskulason commented on snap/hooks/install
> +        "$SNAP_DATA/config/device-camera/res/devices"
As above, should be
```
 cp -r "$SNAP/config/device-camera/res/devices/" \
        "$SNAP_DATA/config/device-camera/res"
```

2021-05-27 20:28 UTC, lenny-intel commented on cmd/res/profiles/camera.yaml
> +  - name: "onvif_device_information"
I think we need a separate issue to fix the resource naming inconstancy, unless you want to do that in this PR also... IMO, it should be pascal case, used for `OnvifHostname`

2021-05-27 20:29 UTC, lenny-intel approved these changes
LGTM

2021-05-28 16:40 UTC, siggiskulason requested changes
Thanks for making the changes - just one bit that needs to be updated - the libzmq version.

2021-05-28 16:40 UTC, siggiskulason commented on snap/snapcraft.yaml
> +    stage-packages: [libzmq4]
This needs to be libzmq5 (not libzmq4). With libzmq4, I get this build error:

```
Failed to fetch stage packages: Error downloading packages for part 'device-camera': The package 'libzmq4' was not found..
```

2021-05-28 17:06 UTC, hahattan commented on snap/snapcraft.yaml
> +    stage-packages: [libzmq4]
fixed

2021-05-28 17:40 UTC, siggiskulason commented
LGTM

2021-05-28 17:41 UTC, siggiskulason approved these changes
LGTM

2021-05-28 22:10 UTC, lenny-intel approved these changes

2021-05-29 12:47 UTC, cloudxxx8 commented on cmd/res/profiles/camera.yaml
> +  - name: "onvif_device_information"
https://github.com/edgexfoundry/device-camera-go/issues/94 is opened for this

2021-05-29 12:48 UTC, merged