feat(security): Get Camera creds from SecretProvider
edgexfoundry/device-camera-go pull request #98
Opened 2021-06-02 18:42 UTC by jim-wang-intel

- Add implementation of getting camera credentials from secret provider / secret store instead of configuration toml directly
- Remove plain text camera credentials from toml config file
- Refactor camera credentials to allow multiple different camera credentials using DeviceList instead of Driver config

Closes: #46
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-camera-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

Currently the credentials of the camera are directly from plain text of TOML file and also only one universal username/password.

## Issue Number:  #46 

## What is the new behavior?
Now, the camera credentials are retrieved from secret store (via secret provider) and can be different for different cameras via using `CredentialPath` under `DeviceList` TOML section.  Just use the same creds path if they are all the same.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## New Imports

- [ ] Yes
- [x ] No

## Specific Instructions

## Other information

2021-06-02 18:43 UTC, jim-wang-intel commented
@siggiskulason / @lenny-intel  Please add reviewer accordingly, thanks!

2021-06-03 17:52 UTC, siggiskulason reviewed
Thanks, this looks good. However, I would like to test it and the device-camera snap doesn't install/run at the moment so that needs to be fixed first. I've created a PR - https://github.com/edgexfoundry/device-camera-go/pull/99 - which resolves hopefully the outstanding issues with starting up the snap, so we would need that reviewed/approved/merged first preferably and then if you could rebase and submit again once that's been merged, then we can test this.

2021-06-03 18:20 UTC, jim-wang-intel commented
> Thanks, this looks good. However, I would like to test it and the device-camera snap doesn't install/run at the moment so that needs to be fixed first. I've created a PR - #99 - which resolves hopefully the outstanding issues with starting up the snap, so we would need that reviewed/approved/merged first preferably and then if you could rebase and submit again once that's been merged, then we can test this.


Sure, no problem. I've added some comments in that PR regarding some step for adding Consul token in env. and dependency on the run-time.

2021-06-08 17:31 UTC, lenny-intel requested changes

2021-06-08 17:31 UTC, lenny-intel commented on internal/driver/driver.go
> +	_, err = d.addrFromProtocols(protocols)
This is just to validate, correct. Can't this be part of CreateCameraInfo?

2021-06-08 17:31 UTC, lenny-intel commented on internal/driver/driver.go
> +		creds, err := GetCredentials(cameraConfig.CredentialPaths)
Need to skip this if AuthMode = none

2021-06-08 17:36 UTC, jim-wang-intel commented on internal/driver/driver.go
> +	_, err = d.addrFromProtocols(protocols)
i;ll need to double check- probably if all callers are getting create camerainfo.

2021-06-08 19:08 UTC, jim-wang-intel commented on internal/driver/driver.go
> +	_, err = d.addrFromProtocols(protocols)
There are two places do not use createCameraInfo and uses addr itself only: 
- Disconnect Device: https://github.com/edgexfoundry/device-camera-go/blob/master/internal/driver/driver.go#L343-L344 
- Remove Device: https://github.com/edgexfoundry/device-camera-go/blob/master/internal/driver/driver.go#L415-L416  

so I think it is still used differently in other place and it is better to leave as it is; otherwise, you will have duplicate codes inside CreateCamerainfo and addrFromProtocols

2021-06-08 20:04 UTC, lenny-intel commented on internal/driver/driver.go
> +	_, err = d.addrFromProtocols(protocols)
Ok

2021-06-08 20:36 UTC, jim-wang-intel commented on internal/driver/driver.go
> +		creds, err := GetCredentials(cameraConfig.CredentialPaths)
fixed.

2021-06-08 22:31 UTC, lenny-intel approved these changes
LGTM

2021-06-08 22:36 UTC, merged