fix(snap): update snap v2 support
edgexfoundry/device-camera-go pull request #99
Opened 2021-06-03 16:15 UTC by siggiskulason

This update fixes a few issues for the v2 update. Specifically:

    - Set adaptor:full to resolve issue with libzmq library not loading

    - Add slot for SecretStore/Vault token and set matching environment variable

    - Use the git tag for versioning, rather than the VERSION file

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-camera-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports

- [ ] Yes
- [ ] No

## Specific Instructions

## Other information

2021-06-03 18:08 UTC, jim-wang-intel commented
Hi @siggiskulason:  If running in secure mode with Consul, we also need to add another environment variable in snap for Consul token to be working:
in [`security-consul-bootstrapper`  snap section](https://github.com/edgexfoundry/edgex-go/blob/master/snap/snapcraft.yaml#L224-L235) , add environment variable: `ADD_REGISTRY_ACL_ROLES` and value is `device-camera`.  It's very similar way to the way to add the Vault token as in your step 1. above.

2021-06-03 18:17 UTC, jim-wang-intel requested changes
requires to add a security-bootstrapper dependency in after section

2021-06-03 18:17 UTC, jim-wang-intel commented on snap/snapcraft.yaml
>      daemon: simple
Add dependency for `security-consul-bootstrapper` in `after` section (using slot?   don't know how you done in this snap but needs that dependency. )

```suggestion
    daemon: simple
    after:
       # This generates the consul role for this service before the service starts      
       - security-consul-bootstrapper
```

2021-06-03 23:07 UTC, tonyespy commented on snap/snapcraft.yaml
>      daemon: simple
@jim-wang-intel unfortunately snapd does not support cross-snap service dependencies, so this is not possible. That said, device services have a configurable retry mechanism on startup which is used to ensure that it's dependencies are available. Since the main edgexfoundry snap always gates startup of the core-*, support-*, and SMA to be after security-consul-bootstrapper and security-proxy-setup have run, relaying on the SDK startup logic just works. If this is found to a problem (i.e. on a hw constrained device), the startup environment variables can be modified via the snap config hook.

2021-06-03 23:39 UTC, jim-wang-intel commented on snap/snapcraft.yaml
>      daemon: simple
ok, sounds good, thanks @tonyespy for explaining this.

2021-06-03 23:41 UTC, jim-wang-intel commented on snap/snapcraft.yaml
>      daemon: simple
ok so I am seeing this dependency after as resolved . but we do need to introduce that extra env. `ADD_REGISTRY_ACL_ROLES = device-camera`   into `security-consul-bootstrapper` in main snap or at least in the documentation above to state that.

2021-06-04 00:10 UTC, tonyespy submitted a review, later dismissed
I built, installed, and tested per your instructions, and everything worked as advertised.

2021-06-04 12:09 UTC, siggiskulason commented on snap/snapcraft.yaml
>      daemon: simple
@jim-wang-intel - thanks for raising that point. Once we have these device PRs merged we'll also raise a PR for the main edgexfoundry / edgex-go snap where we'll set both ADD_SECRETSTORE_TOKENS and ADD_REGISTRY_ACL_ROLES

2021-06-04 12:40 UTC, siggiskulason commented
force-pushed to rebase against master

2021-06-04 15:13 UTC, jim-wang-intel commented on snap/snapcraft.yaml
>      daemon: simple
sounds good, @siggiskulason  thanks!

2021-06-04 15:13 UTC, jim-wang-intel approved these changes

2021-06-08 13:35 UTC, iain-anderson approved these changes

2021-06-08 14:22 UTC, merged